spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_route
    username: postgres
    password: smart_route_123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true